/* Gögn: DMC-litaspjald og þýðingar */
window.KS_PALETTE = [
    {c:"White", n:"White", h:"#FEFEFC"},
    {c:"B5200", n:"Snow White", h:"#FDFDFB"},
    {c:"Ecru", n:"Ecru", h:"#F0EAD6"},
    {c:"310", n:"Black", h:"#0A0A0A"},
    {c:"317", n:"Pewter Grey", h:"#6E6864"},
    {c:"318", n:"Steel Grey Light", h:"#A8A8A8"},
    {c:"414", n:"Steel Grey Dark", h:"#787878"},
    {c:"415", n:"Pearl Grey", h:"#D3D3D3"},
    {c:"3033", n:"Mocha Brown V.Lt", h:"#E9DDC6"},
    {c:"3782", n:"Mocha Brown Lt", h:"#BA9D7D"},
    {c:"869", n:"Hazelnut Brown V.Dk", h:"#7C5B3C"},
    {c:"801", n:"Coffee Brown Dk", h:"#5D3B22"},
    {c:"838", n:"Beige Brown V.Dk", h:"#4B3829"},
    {c:"434", n:"Brown Light", h:"#8C5B2C"},
    {c:"435", n:"Brown Very Light", h:"#A6723D"},
    {c:"437", n:"Tan Light", h:"#DDBA8E"},
    {c:"738", n:"Tan Very Light", h:"#E8CAA1"},
    {c:"739", n:"Tan Ultra V.Lt", h:"#F4E2C5"},
    {c:"300", n:"Mahogany V.Dk", h:"#7C2E0F"},
    {c:"349", n:"Coral Dark", h:"#C43329"},
    {c:"350", n:"Coral Medium", h:"#D9574B"},
    {c:"351", n:"Coral", h:"#E46F5F"},
    {c:"352", n:"Coral Light", h:"#F2A38F"},
    {c:"321", n:"Red", h:"#C51E3A"},
    {c:"498", n:"Red Dark", h:"#A1102A"},
    {c:"816", n:"Garnet", h:"#7C1027"},
    {c:"3350", n:"Dusty Rose V.Dk", h:"#A23D57"},
    {c:"3688", n:"Mauve Medium", h:"#C5728F"},
    {c:"3689", n:"Mauve Light", h:"#E5B0C2"},
    {c:"605", n:"Cranberry V.Lt", h:"#F5BACD"},
    {c:"3805", n:"Cyclamen Pink", h:"#DA3C88"},
    {c:"718", n:"Plum", h:"#9C2671"},
    {c:"553", n:"Violet", h:"#84578C"},
    {c:"554", n:"Violet Light", h:"#CCABD2"},
    {c:"208", n:"Lavender V.Dk", h:"#86588D"},
    {c:"209", n:"Lavender Dark", h:"#AA82B6"},
    {c:"210", n:"Lavender Medium", h:"#C9AAD7"},
    {c:"211", n:"Lavender Light", h:"#E6D4EB"},
    {c:"796", n:"Royal Blue Dk", h:"#10326A"},
    {c:"797", n:"Royal Blue", h:"#1B4F9D"},
    {c:"809", n:"Delft Blue", h:"#7D9FDA"},
    {c:"820", n:"Royal Blue V.Dk", h:"#0B2B5F"},
    {c:"995", n:"Electric Blue Dk", h:"#008AB6"},
    {c:"996", n:"Electric Blue Med", h:"#20AED9"},
    {c:"807", n:"Peacock Blue", h:"#4D9EA7"},
    {c:"992", n:"Aquamarine Light", h:"#58B89C"},
    {c:"993", n:"Aquamarine V.Lt", h:"#A3DDC8"},
    {c:"505", n:"Jade Green", h:"#206F4D"},
    {c:"700", n:"Bright Green", h:"#188B3D"},
    {c:"702", n:"Kelly Green", h:"#50B94C"},
    {c:"704", n:"Chartreuse Bright", h:"#9CCC56"},
    {c:"909", n:"Emerald Green V.Dk", h:"#116A35"},
    {c:"911", n:"Emerald Green Med", h:"#239B4D"},
    {c:"954", n:"Nile Green", h:"#7ECC9B"},
    {c:"986", n:"Forest Green V.Dk", h:"#2D4B28"},
    {c:"3346", n:"Hunter Green", h:"#4C7B35"},
    {c:"3348", n:"Yellow Green Light", h:"#B1CA8B"},
    {c:"469", n:"Avocado Green", h:"#7D7B35"},
    {c:"472", n:"Avocado Green U.Lt", h:"#E1E6B1"},
    {c:"444", n:"Lemon Dark", h:"#F7D300"},
    {c:"307", n:"Lemon", h:"#FFDA20"},
    {c:"725", n:"Topaz Medium", h:"#FFCA3D"},
    {c:"726", n:"Topaz Light", h:"#FFDF7B"},
    {c:"783", n:"Topaz Medium Dk", h:"#C89528"},
    {c:"780", n:"Topaz Ultra V.Dk", h:"#8D601E"},
    {c:"741", n:"Tangerine Medium", h:"#FF9C1F"},
    {c:"740", n:"Tangerine", h:"#FF8300"},
    {c:"947", n:"Burnt Orange", h:"#FF6B3A"},
    {c:"900", n:"Burnt Orange Dark", h:"#B5470F"}
];

window.KS_STRINGS = {
    is: {
      themeLight: "Ljóst",
      themeDark: "Dökkt",
      nameFieldLabel: "Heiti mynsturs",
      nameFieldPlaceholder: "T.d. „Blómakort fyrir ömmu“",
      toolDrawTitle: "Teikna með völdum lit",
      toolDraw: "Teikna",
      toolEraseTitle: "Eyða reitum",
      toolErase: "Eyða",
      toolBackstitchTitle: "Teikna bakspor (útlínur) — smelltu og dragðu milli punkta á netinu, hægrismelltu til að eyða línu",
      toolBackstitch: "Bakspor",
      toolFillTitle: "Fylla samliggjandi svæði með völdum lit",
      toolFill: "Fylla",
      toolLineTitle: "Draga beina línu — smelltu og dragðu, línan er teiknuð þegar þú sleppir",
      toolLine: "Lína",
      toolRectTitle: "Teikna ferning (útlínu) — smelltu og dragðu, haltu Shift inni til að fylla hann",
      toolRect: "Kassi",
      toolPickTitle: "Velja lit af mynstrinu (eða haltu Alt inni og smelltu)",
      toolPick: "Pikka lit",
      undoTitle: "Afturkalla síðustu breytingu",
      undoBtn: "Afturkalla",
      redoTitle: "Endurtaka breytinguna sem var afturkölluð",
      redoBtn: "Endurtaka",
      clearTitle: "Hreinsa allt mynstrið",
      clearBtn: "Hreinsa allt",
      zoomOutTitle: "Minnka reiti",
      zoomInTitle: "Stækka reiti",
      fitTitle: "Passa mynstrið á skjáinn",
      stitchViewBtn: "Sjá það saumað",
      stitchViewTitle: "Sjá mynstrið eins og það kemur út saumað",
      progressBtn: "Saumahamur",
      progressTitle: "Saumahamur — merktu reitina sem þú ert búin með; smelltu aftur til að taka merkinguna af",
      progressLine: "{done} af {total} · {pct}%",
      progressReset: "Núllstilla",
      progressResetTitle: "Tekur allar merkingar af — mynstrið sjálft breytist ekki",
      progressThreadTitle: "Merkja allan þráðinn saumaðan",
      progressRemaining: "{n} eftir",
      progressDoneWord: "búið",
      fitBtn: "Passa á skjá",
      zoomFieldTitle: "Skrifaðu prósentutölu og ýttu á Enter — 100% er raunstærð",
      zoomFieldAria: "Aðdráttur í prósentum",
      genToggleLabel: "Búa til mynstur",
      moreSettingsLabel: "Fleiri stillingar",
      saveToggleLabel: "Vista",
      genTabImage: "Úr mynd",
      genTabLetters: "Skrifa texta",
      genImageBtn: "Búa til úr mynd",
      genBrightLabel: "Birta",
      genContrastLabel: "Birtuskil",
      genResetAdjBtn: "Núllstilla birtu",
      genResetAdjTitle: "Núllstillir birtu og birtuskil",
      genOwnOnlyLabel: "Bara þræðirnir mínir",
      traceLabel: "Hafa myndina undir netinu",
      traceNoFile: "Veldu fyrst mynd til að hafa undir netinu.",
      genMaxColorsLabel: "Fjöldi lita",
      genMaxColorsUnlimited: "Óheft",
      genFitLabel: "Rammi",
      genFitGrid: "Laga netið að myndinni",
      genFitCrop: "Halda stærðinni og klippa",
      genCropLabel: "Klippa",
      genCropCenter: "Úr miðju",
      genCropStart: "Efst / vinstra megin",
      genCropEnd: "Neðst / hægra megin",
      lettersInputPlaceholder: "T.d. „Amma Sigga“ — ein lína fyrir hverja línu í mynstrinu",
      lettersLineGapLabel: "Bil milli lína",
      lettersFontSiena: "Mjótt",
      lettersFontScript: "Tengiskrift",
      lettersFontSerif: "Serif",
      lettersFontRegular: "Einfalt",
      lettersFontStitch: "Bakspor",
      lettersFontLabel: "Skrift",
      lettersHeightLabel: "Hæð stafa",
      flipHTitle: "Spegla mynstrið lárétt",
      flipHBtn: "Spegla lárétt",
      flipVTitle: "Spegla mynstrið lóðrétt",
      flipVBtn: "Spegla lóðrétt",
      rotateTitle: "Snúa mynstrinu 90°",
      rotateBtn: "Snúa 90°",
      centerBtn: "Miðja mynstrið",
      toolSelect: "Velja svæði",
      toolSelectTitle: "Velja svæði til að afrita eða færa — smelltu og dragðu yfir reitina",
      selHintArea: "Valið svæði",
      selHintPlace: "Smelltu þar sem það á að lenda",
      selHintClip: "Bútur tilbúinn",
      selCopyBtn: "Afrita",
      selCutBtn: "Klippa",
      selDeleteBtn: "Eyða",
      pasteBtn: "Líma",
      stampFlipHBtn: "Spegla ↔",
      stampFlipVBtn: "Spegla ↕",
      stampRotateBtn: "Snúa 90°",
      stampPlaceBtn: "Setja hér",
      selCancelBtn: "Hætta við",
      centerTitle: "Miðja mynstrið á blaðinu",
      mirrorLabel: "Speglun",
      mirrorOff: "Engin",
      mirrorH: "Til hliðar",
      mirrorV: "Upp og niður",
      mirrorBoth: "Fjórfalt",
      transformLabel: "Umbreyta",
      shapeLabel: "Lögun",
      shapeRect: "Rétthyrningur",
      shapeCircle: "Útsaumshringur",
      hoopSizeLabel: "Hringstærð",
      sizeLabel: "Stærð",
      widthLabel: "Breidd",
      heightLabel: "Hæð",
      fabricLabel: "Efni",
      aidaCountLabel: "Aida-taldning",
      aida28: "28-count (evenweave, 2 þræðir)",
      symbolsToggle: "Tákn á reitum",
      printToggle: "Prenthamur (svart/hvítt)",
      bgColorLabel: "Bakgrunnslitur",
      coordsToggle: "Röð- og dálkanúmer",
      actualSizeTitle: "Sýnir mynstrið í réttri raunstærð — nákvæmnin ræðst af kvörðun skjásins hér að neðan.",
      actualSizeBtn: "Raunstærð",
      calibrateToggleBtn: "📏 Kvarða skjá",
      calibrateLabel: "Kvörðun skjás",
      calibrateHelp: "Mældu strikið hér að neðan með málbandi eða reglustiku og skráðu nákvæma lengd — þá verður „Raunstærð“ nákvæm á þessum skjá.",
      calibrateInputLabel: "Lengd (cm)",
      calibrateSaveBtn: "Vista kvörðun",
      calibrateSaved: "Vistað — raunstærð er núna kvörðuð á þennan skjá.",
      calibrateInvalid: "Sláðu inn gilda lengd í cm.",
      helpHeading: "Leiðbeiningar",
      helpTitle: "Leiðbeiningar og flýtilyklar",
      closeBtn: "Loka",
      helpSecTools: "Verkfæri",
      helpSecChart: "Á netinu",
      helpSecTouch: "Á spjaldtölvu og síma",
      helpTouchFlow: "Fingurinn teiknar eins og músin: strjúktu yfir reitina til að sauma og notaðu strokleðrið til að taka út. Tveir fingur hreyfa myndina — dragðu með tveimur til að renna til hliðar og upp og niður, klíptu saman eða teygðu í sundur til að minnka og stækka. Ef fyrri fingurinn nær að setja niður spor um leið og þú byrjar hreyfinguna er það sjálfkrafa tekið til baka. Þegar bútur eða texti bíður sýnir fyrsta snertingin hvar hann lendir og sú næsta setur hann niður — eða þú ýtir á „Setja hér“.",
      helpSecUndo: "Afturkalla",
      helpSecSelect: "Velja, afrita og líma",
      helpSecText: "Texti",
      helpSecMirror: "Speglun",
      helpSecImage: "Úr mynd",
      helpSecThreads: "Þræðir",
      helpSecSave: "Vista og skrár",
      helpDraw: "Teikna með völdum þræði",
      helpFill: "Fylla samliggjandi svæði",
      helpLine: "Draga beina línu",
      helpRect: "Kassi — Shift meðan þú dregur fyllir hann",
      helpBack: "Bakspor milli punkta á netinu",
      helpErase: "Eyða reitum",
      helpPick: "Pikka lit af mynstrinu",
      helpSelectTool: "Velja svæði",
      helpKeyRight: "Hægrismellur",
      helpRightClick: "Eyðir spori eða baksporslínu — haltu inni og dragðu til að strjúka út margar í röð",
      helpKeyAlt: "Alt + smellur",
      helpAltClick: "Pikkar litinn undir bendlinum",
      helpKeyStitchView: "Sjá það saumað",
      helpStitchView: "Hnappur við hlið stækkunarinnar — sýnir mynstrið sem krossa á striga í stað reita",
      helpKeyArrows: "Örvatakkar",
      helpArrows: "Færa mynstrið um einn reit",
      helpKeyShiftArrows: "Shift + örvar",
      helpArrowsBig: "Færa um tíu reiti í einu",
      helpKeySpace: "Bilstöng + draga",
      helpPan: "Færa útsýnið (líka með miðjuhnappi músar)",
      helpKeyDelete: "Delete / Backspace",
      helpDeleteKey: "Eyðir sporunum inni í valda svæðinu",
      helpKeyClip: "Ctrl/⌘ + C, X, V",
      helpClipKeys: "Afrita, klippa og líma valda svæðið",
      helpKeyEsc: "Esc",
      helpEsc: "Hættir við bút sem bíður, val og bútinn sem var afritaður",
      helpKeyUndo: "Ctrl/⌘ + Z",
      helpUndo: "Afturkalla síðustu breytingu",
      helpKeyRedo: "Ctrl/⌘ + Shift + Z",
      helpRedo: "Endurtaka það sem var afturkallað",
      helpSelectFlow: "Dragðu ramma um svæði, veldu svo Afrita, Klippa eða Eyða. Bútinn má spegla og snúa um 90° áður en þú smellir þar sem hann á að lenda. Líma setur sama bútinn niður aftur, eins oft og þú vilt, og Ctrl/\u2318 + C, X og V virka líka. „Hætta við“ — eða Esc — hættir við allt saman og hendir bútnum, og þá fer stikan af skjánum.",
      helpTextFlow: "Hver lína í textareitnum verður ein lína í mynstrinu og þær miðjast hver yfir aðra. Textinn eltir bendilinn um leið og þú skrifar — smelltu á mynstrið þar sem hann á að lenda, eða notaðu „Setja hér“. Skiptirðu um skrift, hæð stafa eða þráð breytist hann strax undir bendlinum, og netið stækkar ekki þótt textinn sé of stór; þá segir glugginn þér frá því.",
      helpMirrorFlow: "Teiknaðu einn fjórðung og hitt speglast sjálfkrafa um miðju blaðsins. Speglunin nær til pennans, fötunnar, línunnar, kassans og bakspora — líka þegar þú eyðir, og baksporslína tekur spegilmynd sína með sér. Bútur sem þú límir og texti sem þú setur niður lenda hins vegar bara þar sem þú smellir.",
      helpImageFlow: "Myndin fyllir allt netið og hver reitur fær næsta DMC-lit. „Fjöldi lita“ ræður hversu margir þræðir eru notaðir — allt frá einum upp í fjörutíu eða óheft; einn litur á mynd með gegnsæjum bakgrunni gefur skuggamynd af forminu. Birta og birtuskil teikna myndina upp á nýtt strax og „Núllstilla birtu“ setur þá aftur á núll, og „Bara þræðirnir mínir“ notar eingöngu þá þræði sem þú hefur merkt. Viljirðu frekar teikna sjálf eftir myndinni, hakaðu við „Hafa myndina undir netinu“ — þá liggur hún dauf undir og þú velur hvert spor. Hún fylgir hvorki mynstrinu né því sem þú sækir.",
      helpThreadsFlow: "Merktu þræðina sem þú átt í litaspjaldinu; þeir fá punkt og geymast áfram. „Skipta um þráð“ neðst í skránni skiptir einum þræði út fyrir annan alls staðar — veljir þú lit sem er þegar í mynstrinu renna þeir saman í einn.",
      helpSecProgress: "Saumahamur",
      helpProgressFlow: "Hnappurinn með hakinu, við hliðina á „Sjá það saumað“, setur mynstrið í saumaham. Þá teiknarðu ekki lengur heldur merkir: smelltu á reit sem þú ert búin með og hann fölnar undir haki, smelltu aftur (eða hægrismelltu) til að taka merkinguna af, og dragðu yfir til að merkja margar í röð. Í litaskránni stendur þá hvað er eftir af hverjum þræði og þar er hnappur til að haka heilan þráð við í einu, og efst er súla sem sýnir hve langt þú ert komin. Merkingarnar tilheyra mynstrinu og geymast með því, en þær koma hvorki í PNG-myndina né PDF-ið. „Núllstilla“ tekur þær allar af — mynstrið sjálft breytist ekki.",
      helpSecSize: "Stærð, striginn og hringurinn",
      helpSecSheet: "Útlit blaðsins",
      helpSecPdf: "Hvað er í PDF-inu",
      helpChartFlow: "Stækkunin er í stikunni: − og + stækka reitina, ramminn passar mynstrið á skjáinn og „Raunstærð“ undir Fleiri stillingum sýnir það í réttri stærð miðað við strigann. Prósentutalan milli − og + er líka reitur sem má skrifa í: sláðu inn tölu og ýttu á Enter til að fara beint í þá stækkun — 100% er raunstærð.",
      helpSizeFlow: "Stærð netsins stillirðu annaðhvort undir Fleiri stillingum eða efst í myndaglugganum — það eru sömu reitirnir. Aida-taldningin segir hve mörg spor eru á tommu og ræður því hvað mynstrið mælist í sentimetrum; „Saumfar“ bætir við spássíu allan hringinn og segir þér hve stóran bút á að klippa. Veljirðu útsaumshring í staðinn fyrir rétthyrning ræður hringstærðin netinu og hornin eru falin — þau koma öll til baka þegar þú skiptir aftur yfir í rétthyrning. Neðst er „Kvarða skjá“ ef raunstærðin á að vera nákvæm á þínum skjá.",
      helpSheetFlow: "Undir Fleiri stillingum: „Tákn á reitum“ setur lítið merki — hring, þríhyrning, tígul og svo framvegis — í hvern reit svo hægt sé að sauma eftir svarthvítu blaði; sama merki stendur fyrir þráðinn í litaskránni og í PDF-inu, „Prenthamur“ tekur alla liti af, „Röð- og dálkanúmer“ setja tölur á kantana og „Bakgrunnslitur“ er liturinn á striganum sjálfum. Dökki krossinn um miðjuna er alltaf sýnilegur og segir þér hvar miðja mynstursins er.",
      helpPdfFlow: "PDF-ið er saumblaðið sjálft: fyrst yfirlit yfir allt mynstrið, svo örkin eða arkirnar í stærð sem hægt er að sauma eftir, með röð- og dálkanúmerum á köntunum. Aftast er litaskráin — hver þráður með sínu tákni og fjölda spora, og garnþörfin í metrum. Þar eru alltaf rúður og tákn, líka þótt þú sért að skoða mynstrið saumað á skjánum.",
      helpSaveFlow: "Mynstrin vistast í þessum vafra og það sem þú ert að vinna í kemur aftur næst þegar þú opnar síðuna, líka þótt þú hafir ekki vistað. „Mynstursskrá“ sækir eitt mynstur og „Allt safnið“ öll í einu — afrit sem þú getur geymt annars staðar eða flutt á aðra tölvu, og „Opna úr skrá“ les hvort tveggja aftur inn. PNG-myndin sýnir það sem þú sérð á skjánum, saumaða útlitið líka, en PDF-ið er alltaf saumblaðið með rúðum og táknum.",
      helpColorNote: "Litirnir á skjánum eru eftirlíking — garnið sjálft getur verið aðeins dekkra eða ljósara, svo berðu saman við litakort áður en þú kaupir.",
      paletteHeading: "DMC þræðir",
      myThreadsOnlyLabel: "Bara þræðirnir mínir",
      myThreadsEditBtn: "Merkja þræðina mína",
      myThreadsDoneBtn: "Búin að merkja",
      myThreadsCount: "{n} merktir",
      myThreadsHint: "Smelltu á þá þræði sem þú átt.",
      myThreadsNone: "Þú hefur ekki merkt neinn þráð enn.",
      selectAColor: "Veldu lit",
      legendHeading: "Skrá",
      flossToggleLabel: "Garnþörf",
      legendEmpty: "Engir reitir litaðir enn — veldu þráð og teiknaðu á netið.",
      swapHeading: "Skipta um þráð",
      swapBtn: "Skipta",
      swapDone: "{n} sporum breytt úr DMC {from} í DMC {to}.",
      swapNothing: "Ekkert að skipta — veldu tvo ólíka þræði.",
      totalFloss: "Samtals garn",
      saveBtn: "Vista mynstur",
      saveAsBtn: "Vista sem nýtt",
      newBtn: "Nýtt mynstur",
      saveBlockPattern: "Mynstrið",
      saveBlockFiles: "Skrár",
      exportBtn: "Mynd (PNG)",
      exportPdfBtn: "PDF",
      savedPatternsHeading: "Vistuð mynstur",
      noSavedPatterns: "Engin mynstur vistuð enn.",
      unnamedPattern: "Ónefnt mynstur",
      openBtn: "Opna",
      delBtn: "Eyða",
      downloadImageUnavailable: "Ekki hægt að sækja mynd í þessari skoðun núna.",
      exportFileBtn: "Mynstursskrá",
      exportFileTitle: "Sækir mynstrið sjálft — afrit sem þú getur geymt eða sent áfram",
      importFileBtn: "Opna úr skrá",
      importFileTitle: "Opnar mynstur úr skrá sem þú hefur sótt",
      downloadFileUnavailable: "Ekki hægt að sækja skrá í þessari skoðun núna.",
      fileSaved: "Mynstursskrá vistuð.",
      fileSaveFailed: "Ekki tókst að vista skrána.",
      fileOpened: "„{name}“ opnað úr skrá — mundu að vista það ef þú vilt geyma það hér.",
      fileBad: "Þetta lítur ekki út fyrir að vera mynstursskrá frá Krosssaumi.",
      draftRestored: "Hélt áfram með „{name}“ — það sem var á netinu síðast.",
      exportAllBtn: "Allt safnið",
      exportAllTitle: "Sækir öll vistuðu mynstrin í einni skrá",
      libraryNone: "Engin mynstur til að sækja.",
      librarySaved: "{n} mynstur sótt í einni skrá.",
      libraryOpened: "{n} mynstur sett inn í safnið.",
      imageSaved: "Mynd vistuð.",
      imageSaveFailed: "Ekki tókst að vista mynd.",
      downloadPdfUnavailable: "Ekki hægt að sækja PDF í þessari skoðun núna.",
      pdfLibFailed: "PDF-safn náði ekki að hlaðast — reyndu aftur.",
      pdfSaved: "PDF vistað.",
      pdfSaveFailed: "Ekki tókst að vista PDF.",
      imgBusy: "Vinn úr mynd…",
      imgReady: "Mynstur búið til úr myndinni — {n} spor.",
      imgReadFailed: "Ekki tókst að lesa myndina.",
      lettersStitchEmpty: "Ekkert kom út — prófaðu annan texta (bakspors-stafrófið styður bókstafi, tölur og algeng greinarmerki).",
      lettersEmpty: "Ekkert kom út — prófaðu annan texta.",
      lettersFollow: "Smelltu á mynstrið þar sem textinn á að lenda.",
      lettersTooBig: "Textinn er stærri en netið — hluti hans kemst ekki fyrir. Minnkaðu stafina eða stækkaðu netið.",
      relJustNow: "rétt í þessu",
      relMinAgo: "{n} mín síðan",
      relHourAgo: "{n} klst síðan",
      relDayAgo: "{n} dögum síðan",
      fabricSizeTemplate: "{cmW}×{cmH} cm ({inW}×{inH} tommur) á {count}-count aida",
      marginLabel: "Saumfar",
      fabricCutTemplate: "Klipptu {cmW}×{cmH} cm af striga ({inW}×{inH} tommur) með {m} cm saumfari allan hringinn",
      stitchesAndColors: "{total} spor · {colors} litir",
      flossLine: "{cm} cm · {skeins} hespa",
      pdfLegendHeading: "Skrá",
      pdfFlossLine: "Áætluð garnþörf samtals: u.þ.b. {m} m (viðmiðunartala, miðað við {count}-count).",
      pdfOverviewNote: "Yfirlit — mynstrinu er skipt á {n} blöð hér á eftir, númerin sýna hvaða blað á við hvern hluta.",
      pdfSheetHeader: "Blað {k} af {n} · dálkar {x1}–{x2} · raðir {y1}–{y2}",
      savedNotice: "„{name}“ vistað.",
      savedAsNewNotice: "„{name}“ vistað sem nýtt mynstur.",
      storageFull: "Geymslan í vafranum er full — eyddu mynstri til að vista fleiri.",
      savedRowMeta: "{w}×{h} · {n} spor · {fsize} · {rel}",
      wordStitches: "spor",
      wordColors: "litir"
    },
    en: {
      themeLight: "Light",
      themeDark: "Dark",
      nameFieldLabel: "Pattern name",
      nameFieldPlaceholder: "E.g. \"Flower card for grandma\"",
      toolDrawTitle: "Draw with the selected color",
      toolDraw: "Draw",
      toolEraseTitle: "Erase stitches",
      toolErase: "Erase",
      toolBackstitchTitle: "Draw backstitch (outline) — click and drag between grid points, right-click to remove a line",
      toolBackstitch: "Backstitch",
      toolFillTitle: "Fill a connected area with the selected color",
      toolFill: "Fill",
      toolLineTitle: "Draw a straight line — click and drag, the line is drawn when you let go",
      toolLine: "Line",
      toolRectTitle: "Draw a box (outline) — click and drag, hold Shift to fill it",
      toolRect: "Box",
      toolPickTitle: "Pick a color from the pattern (or hold Alt and click)",
      toolPick: "Pick color",
      undoTitle: "Undo the last change",
      undoBtn: "Undo",
      redoTitle: "Redo the change you undid",
      redoBtn: "Redo",
      clearTitle: "Clear the whole pattern",
      clearBtn: "Clear all",
      zoomOutTitle: "Shrink stitches",
      zoomInTitle: "Enlarge stitches",
      fitTitle: "Fit the pattern on screen",
      stitchViewBtn: "See it stitched",
      stitchViewTitle: "See the pattern as it comes out in thread",
      progressBtn: "Stitching mode",
      progressTitle: "Stitching mode — tick off the squares you have sewn; click again to take a tick back",
      progressLine: "{done} of {total} · {pct}%",
      progressReset: "Reset",
      progressResetTitle: "Takes every tick off — the pattern itself is untouched",
      progressThreadTitle: "Mark this whole thread as stitched",
      progressRemaining: "{n} left",
      progressDoneWord: "done",
      fitBtn: "Fit to screen",
      zoomFieldTitle: "Type a percentage and press Enter — 100% is actual size",
      zoomFieldAria: "Zoom, in percent",
      genToggleLabel: "Generate pattern",
      moreSettingsLabel: "More settings",
      saveToggleLabel: "Save",
      genTabImage: "From image",
      genTabLetters: "Add text",
      genImageBtn: "Generate from image",
      genBrightLabel: "Brightness",
      genContrastLabel: "Contrast",
      genResetAdjBtn: "Reset brightness",
      genResetAdjTitle: "Puts brightness and contrast back to nothing",
      genOwnOnlyLabel: "Only my threads",
      traceLabel: "Keep the photo under the grid",
      traceNoFile: "Choose a photo first to put under the grid.",
      genMaxColorsLabel: "Number of colors",
      genMaxColorsUnlimited: "Unlimited",
      genFitLabel: "Framing",
      genFitGrid: "Fit the grid to the image",
      genFitCrop: "Keep the size and crop",
      genCropLabel: "Crop",
      genCropCenter: "From the middle",
      genCropStart: "Top / left",
      genCropEnd: "Bottom / right",
      lettersInputPlaceholder: "E.g. \"Grandma Sigga\" — one line here is one line on the chart",
      lettersLineGapLabel: "Line spacing",
      lettersFontSiena: "Narrow",
      lettersFontScript: "Joined script",
      lettersFontSerif: "Serif",
      lettersFontRegular: "Plain",
      lettersFontStitch: "Backstitch",
      lettersFontLabel: "Alphabet",
      lettersHeightLabel: "Letter height",
      flipHTitle: "Flip the pattern horizontally",
      flipHBtn: "Flip horizontal",
      flipVTitle: "Flip the pattern vertically",
      flipVBtn: "Flip vertical",
      rotateTitle: "Rotate the pattern 90°",
      rotateBtn: "Rotate 90°",
      centerBtn: "Centre the pattern",
      toolSelect: "Select an area",
      toolSelectTitle: "Select an area to copy or move — click and drag across the squares",
      selHintArea: "Selected area",
      selHintPlace: "Click where it should go",
      selHintClip: "Piece ready",
      selCopyBtn: "Copy",
      selCutBtn: "Cut",
      selDeleteBtn: "Delete",
      pasteBtn: "Paste",
      stampFlipHBtn: "Mirror ↔",
      stampFlipVBtn: "Mirror ↕",
      stampRotateBtn: "Turn 90°",
      stampPlaceBtn: "Place here",
      selCancelBtn: "Cancel",
      centerTitle: "Centre the pattern on the chart",
      mirrorLabel: "Mirror",
      mirrorOff: "None",
      mirrorH: "Sideways",
      mirrorV: "Up and down",
      mirrorBoth: "Four ways",
      transformLabel: "Transform",
      shapeLabel: "Shape",
      shapeRect: "Rectangle",
      shapeCircle: "Embroidery hoop",
      hoopSizeLabel: "Hoop size",
      sizeLabel: "Size",
      widthLabel: "Width",
      heightLabel: "Height",
      fabricLabel: "Fabric",
      aidaCountLabel: "Aida count",
      aida28: "28-count (evenweave, 2 threads)",
      symbolsToggle: "Symbols on stitches",
      printToggle: "Print mode (black/white)",
      bgColorLabel: "Background color",
      coordsToggle: "Row and column numbers",
      actualSizeTitle: "Shows the pattern at true actual size — accuracy depends on the screen calibration below.",
      actualSizeBtn: "Actual size",
      calibrateToggleBtn: "📏 Calibrate screen",
      calibrateLabel: "Screen calibration",
      calibrateHelp: "Measure the bar below with a tape measure or ruler and enter the exact length — then \"Actual size\" will be accurate on this screen.",
      calibrateInputLabel: "Length (cm)",
      calibrateSaveBtn: "Save calibration",
      calibrateSaved: "Saved — actual size is now calibrated to this screen.",
      calibrateInvalid: "Enter a valid length in cm.",
      helpHeading: "How it works",
      helpTitle: "Help and keyboard shortcuts",
      closeBtn: "Close",
      helpSecTools: "Tools",
      helpSecChart: "On the chart",
      helpSecTouch: "On a tablet or phone",
      helpTouchFlow: "A finger draws just like the mouse: sweep across the squares to stitch, and use the eraser to take them out. Two fingers move the view — drag with two to slide the chart, pinch or spread to zoom out and in. If the first finger happens to lay a stitch down as the gesture begins, it is taken back for you. When a piece or some text is waiting, the first tap shows where it would land and the next one puts it there — or press \u201cplace here\u201d.",
      helpSecUndo: "Undo",
      helpSecSelect: "Select, copy and paste",
      helpSecText: "Text",
      helpSecMirror: "Mirroring",
      helpSecImage: "From a photo",
      helpSecThreads: "Threads",
      helpSecSave: "Saving and files",
      helpDraw: "Draw with the chosen thread",
      helpFill: "Fill a connected area",
      helpLine: "Draw a straight line",
      helpRect: "Box — hold Shift while dragging to fill it",
      helpBack: "Backstitch between points on the grid",
      helpErase: "Erase stitches",
      helpPick: "Pick a colour off the chart",
      helpSelectTool: "Select an area",
      helpKeyRight: "Right-click",
      helpRightClick: "Removes a stitch or a backstitch line — hold and drag to rub out a run of them",
      helpKeyAlt: "Alt + click",
      helpAltClick: "Picks the colour under the pointer",
      helpKeyStitchView: "See it stitched",
      helpStitchView: "The button beside the zoom — shows the pattern as crosses on cloth instead of squares",
      helpKeyArrows: "Arrow keys",
      helpArrows: "Move the pattern one square",
      helpKeyShiftArrows: "Shift + arrows",
      helpArrowsBig: "Move ten squares at a time",
      helpKeySpace: "Space + drag",
      helpPan: "Move the view (the middle mouse button works too)",
      helpKeyDelete: "Delete / Backspace",
      helpDeleteKey: "Clears the stitches inside the selection",
      helpKeyClip: "Ctrl/⌘ + C, X, V",
      helpClipKeys: "Copy, cut and paste the selected area",
      helpKeyEsc: "Esc",
      helpEsc: "Cancels a waiting piece, a selection and the copied piece",
      helpKeyUndo: "Ctrl/⌘ + Z",
      helpUndo: "Undo the last change",
      helpKeyRedo: "Ctrl/⌘ + Shift + Z",
      helpRedo: "Redo what was undone",
      helpSelectFlow: "Drag a box around an area, then choose Copy, Cut or Delete. The piece can be mirrored and turned 90° before you click where it should land. Paste puts the same piece down again, as often as you like, and Ctrl/\u2318 + C, X and V work as well. Cancel \u2014 or Esc \u2014 drops the lot: the kept piece is thrown away and the bar leaves the screen.",
      helpTextFlow: "Each line in the text box becomes one line on the chart, centred over each other. The text hangs off the pointer as soon as you type — click the chart where it should land, or use \u201cplace here\u201d. Changing the alphabet, the letter height or the thread rebuilds it on the spot, and the grid is never enlarged to fit: text that is too big is reported as too big.",
      helpMirrorFlow: "Draw one quarter and the rest is mirrored about the middle of the chart. It covers the pen, the bucket, the line, the box and backstitch — erasing too, and rubbing out a backstitch line takes its reflection with it. A pasted piece and placed text land only where you click.",
      helpImageFlow: "The photo fills the whole grid and every stitch gets its nearest DMC colour. \u201cNumber of colours\u201d decides how many threads are used — anything from one to forty, or no limit; one colour on a picture with a see-through background gives a silhouette of the shape. Brightness and contrast redraw it at once and \u201creset brightness\u201d puts them back to nothing, and \u201conly my threads\u201d uses just the ones you have marked. To draw it by hand instead, tick \u201ckeep the photo under the grid\u201d — it then lies faintly underneath and you pick every stitch. It is part of neither the pattern nor anything you download.",
      helpThreadsFlow: "Mark the threads you own in the palette; they get a dot and are remembered. \u201cSwap a thread\u201d at the bottom of the list replaces one thread with another everywhere — pick one already in the pattern and the two merge into one.",
      helpSecProgress: "Stitching mode",
      helpProgressFlow: "The tick button beside “see it stitched” puts the chart into stitching mode. You are no longer drawing but marking: click a square you have sewn and it fades under a tick, click it again (or right-click) to take the tick back, and drag across to mark a run of them. The thread list then says how many squares are left in each colour and carries a button to tick off a whole thread at once, and a bar at the top shows how far along you are. The ticks belong to the pattern and are saved with it, but they stay out of the PNG and the PDF. “Reset” takes them all off — the pattern itself is untouched.",
      helpSecSize: "Size, fabric and hoop",
      helpSecSheet: "How the chart looks",
      helpSecPdf: "What is in the PDF",
      helpChartFlow: "The zoom is in the toolbar: − and + change the size of the squares, the frame fits the pattern on screen, and \u201cactual size\u201d under More settings shows it at its true size on the fabric. The percentage between − and + is a box you can type in: put a number in it and press Enter to go straight to that zoom — 100% is actual size.",
      helpSizeFlow: "The size of the grid is set either under More settings or at the top of the photo pane — they are the same boxes. The aida count says how many stitches go to an inch and decides what the pattern measures in centimetres; \u201cmargin\u201d adds cloth all round and tells you how big a piece to cut. Choose the hoop instead of the rectangle and the hoop size decides the grid, with the corners hidden — they all come back when you switch to the rectangle again. At the bottom, \u201ccalibrate screen\u201d makes actual size exact on your own screen.",
      helpSheetFlow: "Under More settings: \u201csymbols on squares\u201d puts a little mark — a circle, a triangle, a diamond and so on — in every square so the pattern can be stitched from a black-and-white sheet; the same mark stands for that thread in the colour list and in the PDF, \u201cprint mode\u201d takes all the colour off, \u201crow and column numbers\u201d put figures along the edges, and \u201cbackground colour\u201d is the cloth itself. The dark cross through the middle is always there to show where the centre is.",
      helpPdfFlow: "The PDF is the working sheet: an overview of the whole pattern first, then the sheet or sheets at a size you can stitch from, with row and column numbers along the edges. At the back is the thread list — every thread with its symbol and stitch count, and how many metres of floss it takes. It always has the grid and the symbols, even while you are looking at the stitched view on screen.",
      helpSaveFlow: "Patterns are saved in this browser, and whatever you are working on comes back next time you open the page, saved or not. \u201cPattern file\u201d downloads one and \u201cwhole library\u201d all of them at once — backups you can keep elsewhere or move to another computer, and \u201copen from file\u201d reads either back in. The PNG shows what is on your screen, stitched view included, while the PDF is always the working sheet with its grid and symbols.",
      helpColorNote: "The colours on screen are an approximation — real floss can be a little darker or lighter, so compare with a colour card before buying.",
      paletteHeading: "DMC threads",
      myThreadsOnlyLabel: "Only my threads",
      myThreadsEditBtn: "Mark my threads",
      myThreadsDoneBtn: "Done marking",
      myThreadsCount: "{n} marked",
      myThreadsHint: "Click the threads you have.",
      myThreadsNone: "You haven't marked any threads yet.",
      selectAColor: "Choose a color",
      legendHeading: "Legend",
      flossToggleLabel: "Floss needed",
      legendEmpty: "No stitches yet — choose a thread and draw on the grid.",
      swapHeading: "Swap a thread",
      swapBtn: "Swap",
      swapDone: "{n} stitches changed from DMC {from} to DMC {to}.",
      swapNothing: "Nothing to swap — pick two different threads.",
      totalFloss: "Total floss",
      saveBtn: "Save pattern",
      saveAsBtn: "Save as new",
      newBtn: "New pattern",
      saveBlockPattern: "This pattern",
      saveBlockFiles: "Files",
      exportBtn: "Image (PNG)",
      exportPdfBtn: "PDF",
      savedPatternsHeading: "Saved patterns",
      noSavedPatterns: "No patterns saved yet.",
      unnamedPattern: "Untitled pattern",
      openBtn: "Open",
      delBtn: "Delete",
      downloadImageUnavailable: "Can't download an image in this view right now.",
      exportFileBtn: "Pattern file",
      exportFileTitle: "Downloads the pattern itself — a backup you can keep or pass on",
      importFileBtn: "Open from file",
      importFileTitle: "Opens a pattern from a file you downloaded",
      downloadFileUnavailable: "Can't download a file in this view right now.",
      fileSaved: "Pattern file saved.",
      fileSaveFailed: "Couldn't save the file.",
      fileOpened: "\u201c{name}\u201d opened from a file — save it if you want to keep it here.",
      fileBad: "That doesn't look like a Krosssaumur pattern file.",
      draftRestored: "Picked up \u201c{name}\u201d again — what was on the chart last time.",
      exportAllBtn: "Whole library",
      exportAllTitle: "Downloads every saved pattern in one file",
      libraryNone: "No patterns to download yet.",
      librarySaved: "{n} patterns downloaded in one file.",
      libraryOpened: "{n} patterns added to your list.",
      imageSaved: "Image saved.",
      imageSaveFailed: "Couldn't save the image.",
      downloadPdfUnavailable: "Can't download a PDF in this view right now.",
      pdfLibFailed: "The PDF library failed to load — try again.",
      pdfSaved: "PDF saved.",
      pdfSaveFailed: "Couldn't save the PDF.",
      imgBusy: "Processing image…",
      imgReady: "Pattern generated from the image — {n} stitches.",
      imgReadFailed: "Couldn't read the image.",
      lettersStitchEmpty: "Nothing came out — try different text (the backstitch alphabet covers letters, digits and common punctuation).",
      lettersEmpty: "Nothing came out — try different text.",
      lettersFollow: "Click the chart where the text should land.",
      lettersTooBig: "The text is bigger than the grid — part of it will not fit. Use smaller letters, or a bigger grid.",
      relJustNow: "just now",
      relMinAgo: "{n} min ago",
      relHourAgo: "{n} h ago",
      relDayAgo: "{n} days ago",
      fabricSizeTemplate: "{cmW}×{cmH} cm ({inW}×{inH} inches) on {count}-count aida",
      marginLabel: "Margin",
      fabricCutTemplate: "Cut {cmW}×{cmH} cm of fabric ({inW}×{inH} inches) with a {m} cm margin all round",
      stitchesAndColors: "{total} stitches · {colors} colors",
      flossLine: "{cm} cm · {skeins} skein(s)",
      pdfLegendHeading: "Legend",
      pdfFlossLine: "Estimated total floss: approx. {m} m (a rough guide, based on {count}-count).",
      pdfOverviewNote: "Overview — the chart is split across {n} sheets that follow; the numbers show which sheet covers which part.",
      pdfSheetHeader: "Sheet {k} of {n} · columns {x1}–{x2} · rows {y1}–{y2}",
      savedNotice: "\"{name}\" saved.",
      savedAsNewNotice: "\"{name}\" saved as a new pattern.",
      storageFull: "This browser's storage is full — delete a pattern to save more.",
      savedRowMeta: "{w}×{h} · {n} stitches · {fsize} · {rel}",
      wordStitches: "stitches",
      wordColors: "colors"
    }
};
